### ISSUE TITLE
Add environment examples to documentation

### ISSUE THREAD

**Issue by alanablett** [ctidigital/magento2-configurator#35]
I heard of this module via the twittersphere and am intrigued. I think it'd be really helpful in getting some of the stores I am working on up and running.

What I am not sure of is how to implement different configuration based on the environment. The example commands show an environment being passed in, but where do I actually specify that configuration. So for example I want to enable debug mode of a module in development and staging, but not in production. Is that possible, and if so how? Or as per the example master.yml file, is the env var specifically only meant for setting the log level and mode?

Keep up the great work!

**Comment by chevli** [comment]
Hi @alanablett,

Thank you for the question.

Yes, it does appear the master.yaml does not contain an example of how to include configuration for  different environments. I will look to include this.

As an example for now, this should work:

```
config:
  enabled: 1
  method: code
  sources:
    - ../configurator/Configuration/global.yaml
    - ../configurator/Configuration/base-website-config.yaml
  env:
      local:
        sources:
          - ../configurator/Configuration/local.yaml
      live:
        sources:
          - ../configurator/Configuration/live.yaml
```

Using the command `bin/magento configurator:run --env="local" --component="config"` will run the following:
```
../configurator/Configuration/global.yaml
../configurator/Configuration/base-website-config.yaml
../configurator/Configuration/local.yaml
```

And using the command `bin/magento configurator:run --env="live" --component="config"` will run the following:
```
../configurator/Configuration/global.yaml
../configurator/Configuration/base-website-config.yaml
../configurator/Configuration/live.yaml
```

In terms of the logging, its use is still rather experimental and it is likely to be removed. We are considering whether to simply use `-v -vv -vvv` to select the verbosity when we run the configurator command as that is widely accepted. 

In terms of the mode, once the components have better support for the detection of existing database entities, then the mode will dictate whether something (e.g. a category) should be overwritten or skipped. This is likely to be further down the line of development.

Once we're happy with the state and reliability of configurator, we'll likely bump the version number of to version 1. Nevertheless, I hope that clarifies configurator and its current state of development.

Thank you
